services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "
        bunx prisma migrate deploy &&
        bun run index.ts
      "

volumes:
  postgres_data:
